# Generated by Django 5.0.7 on 2024-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='banner',
            field=models.ImageField(blank=True, default='images/default_banner.jpg', null=True, upload_to='static/banners/'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/theme/static/images/default-profile-picture.jpg', null=True, upload_to='static/profile_pictures/'),
        ),
    ]
