# Generated by Django 5.0.7 on 2024-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuserprofile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-profile-picture.jpg', null=True, upload_to='static/profile_pictures/'),
        ),
    ]
