# Generated by Django 5.0.7 on 2024-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuserprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='banner',
            field=models.ImageField(blank=True, default='banners/default_banner.jpg', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile-picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
