# Generated by Django 5.0.7 on 2024-10-06 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_collaboratorrequest_partnerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='campaigns_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
