# Generated by Django 5.0.7 on 2024-10-06 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_alter_campaign_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_partner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
