# Generated by Django 5.0.7 on 2024-10-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_alter_campaign_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='campaigns_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'advertiser'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
